name: Build iOS App

on:
  pull_request:
    paths:
      - ".github/workflows/build-ios.yml"
      - "ios/**"
      - "*.podspec"
      - "example/ios/**"

jobs:
  build:
    name: Build iOS Example App
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true
          cache-version: 2

      - name: Restore Pods cache
        uses: actions/cache@v4
        with:
          path: |
            example/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        working-directory: example/ios
        run: |
          bundle exec pod repo update --verbose
          bundle exec pod install

      - name: Build App
        working-directory: example/ios
        run: "xcodebuild \
          -workspace CompressorExample.xcworkspace \
          -scheme CompressorExample \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination \"generic/platform=iOS Simulator\" \
          build \
          CODE_SIGNING_ALLOWED=NO"
