name: Build Android App

on:
  pull_request:
    paths:
      - ".github/workflows/build-android.yml"
      - "android/**"
      - "example/android/**"
      - "yarn.lock"
      - "example/yarn.lock"

jobs:
  build:
    name: Build Android Example App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: "gradle"

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Gradle Build
        run: |
          cd example/android
          ./gradlew assembleDebug
