name: Validate Android

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/validate-android.yml"
      - "android/**"
      - ".editorconfig"
  pull_request:
    paths:
      - ".github/workflows/validate-android.yml"
      - "android/**"
      - ".editorconfig"

jobs:
  lint:
    name: Gradle Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Setup
        uses: ./.github/actions/setup

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Gradle Lint
        run: ./gradlew lint

      - name: Parse Gradle Lint Report
        uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: android/build/reports/lint-results.xml
