name: Validate Android

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/validate-android.yml"
      - "android/**"
      - ".editorconfig"
  pull_request:
    paths:
      - ".github/workflows/validate-android.yml"
      - "android/**"
      - ".editorconfig"

jobs:
  lint:
    name: Gradle Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack and set yarn to latest stable
        shell: bash
        run: |
          corepack enable
          yarn set version stable

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: gradle

      - name: Run Gradle Lint
        run: ./gradlew lint

      - name: Parse Gradle Lint Report
        uses: yutailang0119/action-android-lint@v4
        with:
          report-path: android/build/reports/lint-results.xml
          ignore-warnings: true # Ignore Lint Warnings
        continue-on-error: false
